---
name:             Invsee
main:             presentkim\inventorymonitor\InventoryMonitor
version:          1.0.3
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim
website:          Not showing.
description:      A plugin show other player's inventory

permissions:
  invsee.cmd:
    description:  InventoryMonitor main command
    default:      op
    children:
      invsee.cmd.view:
        description:  InventoryMonitor command - view
        default:      op
      invsee.cmd.lang:
        description:  InventoryMonitor command - lang
        default:      op
      invsee.cmd.reload:
        description:  InventoryMonitor command - reload
        default:      op
...
