# Advanced configuration file for InventoryMonitor plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

formId:
  # Form id for InventoryMonitor
  # It was determined by the InventoryMonitor repo ID (According to https://api.github.com/repos/PresentKim/InventoryMonitor-PMMP)
  select: 1200960900 #120096090 + 0
  confirm: 1200960901 #120096090 + 1